name: Publish Python Package

on:
  push:
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get OIDC token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"SERVICE_ACCOUNT_SLUG\"}" ${{ secrets.CLOUDSMITH_API_HOST }}/openid/ORGANIZATION/ | jq -r '.token')
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
                    
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Install Cloudsmith CLI
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        env:
          CLOUDSMITH_API_HOST: ${{ secrets.CLOUDSMITH_API_HOST }}
        with:
          pip-install: true
          command: 'ls repos'




# name: OpenID Connect Demo
# run-name: ${{ github.actor }} is testing out GitHub Actions with OpenID Connect 🚀
# on: [push]

# permissions:
#   id-token: write

# jobs:
#   test-openid-connect:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get OIDC Token
#         run: |
#           value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq '.value')
#           echo "$value"
#           token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"teemo\"}" https://api.cloudsmith.io/openid/bart-demo-org/ | jq -r '.token')
#           echo "BTOKEN=Bearer $token" >> $GITHUB_ENV
#           echo "OIDC_TOKEN=$token" >> $GITHUB_ENV

#       - name: Validate token in Cloudsmith
#         run: |
#           curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key: $BTOKEN" --header 'accept: application/json'

#       - uses: actions/checkout@v4
#       - name: Push
#         id: push
#         uses: BartoszBlizniak/action@master
#         with:
#           api-key: $OIDC_TOKEN
#           command: "push"
#           format: "npm"
#           owner: "bart-demo-org"
#           repo: "api-test"
#           tags: "latest, new-tag, squad-test-squad, application-test-app"
#           republish: "true"
#           file: "files/*.tgz"
